View all skills
2002javareact/Curricula-UI pull request #16
Opened 2020-04-05 14:52 UTC by cabrerojesus

2020-04-05 18:36 UTC, Abatson requested changes
Pull from dev first and make sure you get the changes

2020-04-05 19:09 UTC, Gerard-Cancino commented
Hi Jesus! Hope you're having a nice weekend.  Do you mind changing the error class to follow UpperCamelCase?  Thank you!  Or if not, then I'll happily change it when this gets merged.

2020-04-06 15:55 UTC, Abatson requested changes
I left a bunch of comments, but they basically are, make sure you don;t remove anyone else's code that was in dev

2020-04-06 15:55 UTC, Abatson commented on curriculum-ui/package.json
> +    "material-ui": "^0.20.2",
probably don't need this

2020-04-06 15:55 UTC, Abatson commented on curriculum-ui/src/App.test.tsx
> +  expect(linkElement).toBeInTheDocument();
you need the test file from dev, this one is entirely wrong

2020-04-06 15:55 UTC, Abatson commented on curriculum-ui/src/App.tsx
> +        </Switch>
you should probably have the other route in dev as well, because otherwise you are getting rid of someone elses code

2020-04-06 15:55 UTC, Abatson commented on curriculum-ui/src/reducers/index.ts
> +
you are missing the I curriculum state that was in dev

2020-04-06 15:55 UTC, Abatson commented on curriculum-ui/src/reducers/index.ts
> +    createSkill:createSkillReducer
you are also missing the curriculum reducer that was in dev

2020-04-06 17:34 UTC, closed without merging